language: php

php:
  - 7.0
  - 7.1
  - hhvm
  - nightly

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate

script:
  - vendor/bin/phpunit

matrix:
  fast_finish: true
  allow_failures:
  - php: hhvm
  - php: nightly

